<?php
declare(strict_types=1);

/**
 * Mono 核心入口（单核心）。
 *
 * 设计遵循 docs/DEVELOPMENT_RULES.md：零依赖、单核心、数据库抽象、契约优于隔离。
 * 架构参考 bbs1org：Hook 管道 + 万物皆插件，但核心自带完整博客功能，安装即用。
 *
 * 本文件包含：引导、DBAL、认证/CSRF、设置、Hook 与插件运行时、路由、
 * 渲染、Markdown、博客业务与请求分发。安装/后台/插件管理拆分到 app/optional。
 */

use app\optional\Admin;
use app\optional\Plugin;
use app\optional\Setup;

// --- 1. 引导与常量 ---
$remote_addr = (string)($_SERVER['REMOTE_ADDR'] ?? '');
$is_local = in_array($remote_addr, ['127.0.0.1', '::1'], true)
    || str_starts_with($remote_addr, '172.') || str_starts_with($remote_addr, '192.168.');
ini_set('display_errors', $is_local ? '1' : '0');
error_reporting($is_local ? E_ALL : E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED);
date_default_timezone_set('Asia/Shanghai');

define('APP_START_TIME', microtime(true));
define('APP_ROOT', __DIR__);
define('APP_DIR', APP_ROOT . '/app');
define('ASSET_DIR', APP_DIR . '/assets');
define('DATA_DIR', APP_DIR . '/data');
define('DB_CONFIG_FILE', DATA_DIR . '/db.php');
define('INSTALL_LOCK_FILE', DATA_DIR . '/install.lock');
define('PLUGIN_DIR', APP_DIR . '/plugins');
define('PLUGIN_CSS_FILE', ASSET_DIR . '/plugins.css');
define('PLUGIN_JS_FILE', ASSET_DIR . '/plugins.js');
define('COOKIE_TTL', 15552000);
define('AUTH_COOKIE_NAME', 'mono_auth');
define('CSRF_COOKIE_NAME', 'mono_csrf');
define('DB_STRING_MAX_LENGTH', 255);
define('DB_TEXT_MAX_LENGTH', 4294967295);

require APP_DIR . '/version.php';

// app/optional 下的核心类按需自动加载（命名空间 app\optional\）。
spl_autoload_register(static function (string $class): void {
    if (!str_starts_with($class, 'app\\optional\\')) return;
    $file = APP_DIR . '/optional/' . str_replace('\\', '/', substr($class, strlen('app\\optional\\'))) . '.php';
    if (is_file($file)) require_once $file;
});

// PHP 内置服务器（php -S ... index.php）静态资源直通：
// index.php 作为路由脚本会拦截所有请求，此处对真实存在的静态文件 return false，
// 交给内置服务器直接返回（css/js/svg/图片），避免全部走应用逻辑。
// 安全：仅放行根目录内、非 .php 的真实文件，并排除 app/data 运行时目录。
if (PHP_SAPI === 'cli-server') {
    $req = rawurldecode((string)(parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/'));
    $root = realpath(APP_ROOT) ?: APP_ROOT;
    $data = realpath(DATA_DIR) ?: DATA_DIR;
    if ($req !== '/' && !str_contains($req, "\0")) {
        $file = realpath($root . '/' . ltrim($req, '/'));
        if ($file !== false && is_file($file)
            && str_starts_with($file, $root)
            && !str_ends_with($file, '.php')
            && !str_starts_with($file, $data . DIRECTORY_SEPARATOR)) {
            return false;
        }
    }
}

// --- 2. 数据库抽象层 (DBAL) ---
function app_db_config(string $file, string $data_dir): array
{
    $c = is_file($file) ? include $file : [];
    if (!is_array($c)) $c = [];
    $driver = in_array($c['driver'] ?? 'sqlite', ['sqlite', 'mysql', 'pgsql'], true) ? $c['driver'] : 'sqlite';
    if ($driver === 'sqlite') {
        return ['driver' => 'sqlite', 'path' => $data_dir . '/' . ($c['database'] ?? 'blog.sqlite')];
    }
    return [
        'driver' => $driver,
        'host' => (string)($c['host'] ?? '127.0.0.1'),
        'port' => (string)($c['port'] ?? ($driver === 'mysql' ? '3306' : '5432')),
        'database' => (string)($c['database'] ?? ''),
        'username' => (string)($c['username'] ?? ''),
        'password' => (string)($c['password'] ?? ''),
    ];
}

function app_db_connect(array $config): PDO
{
    $opts = [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC];
    $d = $config['driver'];
    if ($d === 'sqlite') {
        if (!is_dir(DATA_DIR)) mkdir(DATA_DIR, 0755, true);
        $db = new PDO('sqlite:' . $config['path'], null, null, $opts);
        $db->exec('PRAGMA journal_mode=WAL');
        $db->exec('PRAGMA foreign_keys=ON');
        return $db;
    }
    if ($d === 'mysql') {
        return new PDO("mysql:host={$config['host']};port={$config['port']};dbname={$config['database']};charset=utf8mb4", $config['username'], $config['password'], $opts);
    }
    return new PDO("pgsql:host={$config['host']};port={$config['port']};dbname={$config['database']}", $config['username'], $config['password'], $opts);
}

function app_db_identifier(string $driver, string $name): string
{
    if (!preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/', $name)) throw new InvalidArgumentException('无效的数据库标识符。');
    return $driver === 'mysql' ? '`' . $name . '`' : '"' . $name . '"';
}

function sql_marks(int $count): string
{
    return implode(',', array_fill(0, max(0, $count), '?'));
}

function app_db_types(?string $driver = null): array
{
    $driver ??= db_driver();
    return [
        'id' => match ($driver) {
            'mysql' => 'INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT',
            'pgsql' => 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            default => 'INTEGER PRIMARY KEY AUTOINCREMENT',
        },
        'uint' => $driver === 'mysql' ? 'INTEGER UNSIGNED' : 'INTEGER',
        'key' => $driver === 'mysql' ? 'VARCHAR(191)' : 'TEXT',
        'string' => $driver === 'mysql' ? 'VARCHAR(255)' : 'TEXT',
        'text' => $driver === 'mysql' ? 'LONGTEXT' : 'TEXT',
    ];
}

function app_db_columns(PDO $db, string $driver, string $table): array
{
    if ($driver === 'sqlite') $rows = $db->query('PRAGMA table_info(' . $table . ')')->fetchAll();
    else {
        $sql = 'SELECT column_name FROM information_schema.columns WHERE table_schema=' . ($driver === 'mysql' ? 'DATABASE()' : 'current_schema()') . ' AND table_name=?';
        $stmt = $db->prepare($sql); $stmt->execute([$table]); $rows = $stmt->fetchAll();
    }
    $columns = [];
    foreach ($rows as $row) {
        $key = $driver === 'sqlite' ? 'name' : 'column_name';
        $column = $row[$key] ?? $row[strtoupper($key)] ?? array_values($row)[0] ?? '';
        $columns[(string)$column] = true;
    }
    return $columns;
}

function app_db_table_exists(PDO $db, string $driver, string $table): bool
{
    $sql = match ($driver) {
        'mysql' => 'SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?',
        'pgsql' => 'SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name=?',
        default => "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
    };
    $stmt = $db->prepare($sql); $stmt->execute([$table]); return (bool)$stmt->fetchColumn();
}

function app_db_index_exists(PDO $db, string $driver, string $index, string $table = ''): bool
{
    $sql = match ($driver) {
        'mysql' => 'SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND index_name=?' . ($table !== '' ? ' AND table_name=?' : ''),
        'pgsql' => 'SELECT 1 FROM pg_indexes WHERE schemaname=current_schema() AND indexname=?' . ($table !== '' ? ' AND tablename=?' : ''),
        default => "SELECT 1 FROM sqlite_master WHERE type='index' AND name=?" . ($table !== '' ? ' AND tbl_name=?' : ''),
    };
    $stmt = $db->prepare($sql); $stmt->execute($table !== '' ? [$index, $table] : [$index]); return (bool)$stmt->fetchColumn();
}

function app_db_upsert_sql(string $driver, string $table, array $columns, array $keys): string
{
    $marks = sql_marks(count($columns));
    $base = 'INSERT INTO ' . app_db_identifier($driver, $table) . '(' . implode(',', $columns) . ') VALUES(' . $marks . ')';
    $updates = array_values(array_diff($columns, $keys));
    if (!$updates) return $driver === 'mysql' ? str_replace('INSERT INTO', 'INSERT IGNORE INTO', $base) : $base . ' ON CONFLICT(' . implode(',', $keys) . ') DO NOTHING';
    if ($driver === 'mysql') return $base . ' ON DUPLICATE KEY UPDATE ' . implode(',', array_map(fn($c) => $c . '=VALUES(' . $c . ')', $updates));
    return $base . ' ON CONFLICT(' . implode(',', $keys) . ') DO UPDATE SET ' . implode(',', array_map(fn($c) => $c . '=excluded.' . $c, $updates));
}

function app_db_write(string $table, array $data, array $keys, bool $ignore = false): void
{
    if (!$data || !$keys) throw new InvalidArgumentException('数据库写入参数不能为空。');
    $columns = array_keys($data);
    $driver = db_driver();
    if ($ignore) {
        $base = 'INSERT INTO ' . app_db_identifier($driver, $table) . '(' . implode(',', $columns) . ') VALUES(' . sql_marks(count($columns)) . ')';
        $sql = $driver === 'mysql' ? str_replace('INSERT INTO', 'INSERT IGNORE INTO', $base) : $base . ' ON CONFLICT(' . implode(',', $keys) . ') DO NOTHING';
    } else $sql = app_db_upsert_sql($driver, $table, $columns, $keys);
    db()->prepare($sql)->execute(array_values($data));
    db_row_cache_clear();
}

function app_db_upsert(string $table, array $data, array $keys): void { app_db_write($table, $data, $keys); }
function app_db_insert_ignore(string $table, array $data, array $keys): void { app_db_write($table, $data, $keys, true); }

function app_db_create_index(string $name, string $target): void
{
    $table = trim((string)strstr($target, '(', true));
    if (app_db_index_exists(db(), db_driver(), $name, $table)) return;
    db()->exec('CREATE INDEX ' . app_db_identifier(db_driver(), $name) . ' ON ' . $target);
}

function app_db_drop_index(string $name, string $table): void
{
    if (!app_db_index_exists(db(), db_driver(), $name, $table)) return;
    $sql = 'DROP INDEX ' . app_db_identifier(db_driver(), $name);
    if (db_driver() === 'mysql') $sql .= ' ON ' . app_db_identifier(db_driver(), $table);
    db()->exec($sql);
}

function app_db_mysql_nullable_lob_defaults(string $definition, bool $with_column_names = true): string
{
    $lob = '(?:TINY|MEDIUM|LONG)?(?:TEXT|BLOB)|JSON';
    $prefix = $with_column_names ? '`?[a-zA-Z0-9_]+`?\\s+' : '';
    $pattern = "/(^|,)\\s*({$prefix}(?:{$lob})(?:\\([^)]*\\))?[^,]*?)\\s+DEFAULT\\s*(?:''|NULL)/is";
    return preg_replace_callback($pattern, static function (array $m): string {
        $col = preg_replace('/\\s+NOT\\s+NULL\\b/i', ' NULL', $m[2]) ?? $m[2];
        return $m[1] . $col;
    }, $definition) ?? $definition;
}

function app_db_create_table(string $table, string $definition): void
{
    if (db_driver() === 'mysql') $definition = app_db_mysql_nullable_lob_defaults($definition);
    $sql = 'CREATE TABLE IF NOT EXISTS ' . app_db_identifier(db_driver(), $table) . '(' . $definition . ')';
    if (db_driver() === 'mysql') $sql .= ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';
    db()->exec($sql);
}

function app_db_drop_table(string $table): void
{
    db()->exec('DROP TABLE IF EXISTS ' . app_db_identifier(db_driver(), $table));
}

function app_db_ensure_columns(string $table, array $definitions): void
{
    $columns = app_db_columns(db(), db_driver(), $table);
    foreach ($definitions as $name => $definition) {
        if (isset($columns[$name])) continue;
        if (db_driver() === 'mysql') $definition = app_db_mysql_nullable_lob_defaults($definition, false);
        db()->exec('ALTER TABLE ' . app_db_identifier(db_driver(), $table) . ' ADD COLUMN ' . app_db_identifier(db_driver(), $name) . ' ' . $definition);
    }
}

function app_db_drop_column(string $table, string $column): void
{
    $db = db(); $driver = db_driver();
    if (!isset(app_db_columns($db, $driver, $table)[$column])) return;
    $db->exec('ALTER TABLE ' . app_db_identifier($driver, $table) . ' DROP COLUMN ' . app_db_identifier($driver, $column));
}

function app_db_last_insert_id(string $table): int
{
    if (db_driver() === 'pgsql') {
        $stmt = db()->prepare("SELECT currval(pg_get_serial_sequence(?, 'id'))");
        $stmt->execute([$table]);
        return (int)$stmt->fetchColumn();
    }
    return (int)db()->lastInsertId();
}

function app_db_greatest(string ...$expressions): string
{
    return (db_driver() === 'sqlite' ? 'MAX' : 'GREATEST') . '(' . implode(',', $expressions) . ')';
}

// --- 3. 连接与查询助手 ---
function db_config(): array
{
    static $config;
    return $config ??= app_db_config(DB_CONFIG_FILE, DATA_DIR);
}
function db_driver(): string { return (string)db_config()['driver']; }
function db(): PDO
{
    static $db;
    return $db ??= app_db_connect(db_config());
}
function db_row_cache_clear(): void { $GLOBALS['__db_row_cache'] = []; }

function q(string $sql, array $p = []): PDOStatement
{
    if (strncasecmp(ltrim($sql), 'SELECT', 6) !== 0) db_row_cache_clear();
    $s = db()->prepare($sql);
    $s->execute($p);
    return $s;
}
function one(string $sql, array $p = []): ?array { $r = q($sql, $p)->fetch(); return $r ?: null; }
function all(string $sql, array $p = []): array { return q($sql, $p)->fetchAll(); }
function val(string $sql, array $p = []): mixed { return q($sql, $p)->fetchColumn(); }

function row(string $table, string $key, mixed $value): ?array
{
    $cache =& $GLOBALS['__db_row_cache'];
    if (!is_array($cache)) $cache = [];
    $cache_key = $table . "\0" . $key . "\0" . serialize($value);
    if (!array_key_exists($cache_key, $cache)) {
        $t = app_db_identifier(db_driver(), $table);
        $k = app_db_identifier(db_driver(), $key);
        $cache[$cache_key] = one("SELECT * FROM $t WHERE $k=?", [$value]) ?: false;
    }
    return $cache[$cache_key] ?: null;
}

function rows_by_ids(string $table, array $ids, string $cols = '*'): array
{
    $ids = array_values(array_unique(array_filter(array_map('intval', $ids))));
    if (!$ids) return [];
    $rows = q("SELECT $cols FROM $table WHERE id IN (" . sql_marks(count($ids)) . ')', $ids)->fetchAll();
    $map = [];
    foreach ($rows as $r) $map[(int)$r['id']] = $r;
    return $map;
}

function tx(callable $fn): mixed
{
    $db = db();
    if ($db->inTransaction()) return $fn();
    $sqlite = db_driver() === 'sqlite';
    if ($sqlite) $db->exec('BEGIN IMMEDIATE'); else $db->beginTransaction();
    try {
        $result = $fn();
        if ($sqlite) $db->exec('COMMIT'); else $db->commit();
        return $result;
    } catch (Throwable $e) {
        if ($sqlite) { try { $db->exec('ROLLBACK'); } catch (Throwable) {} }
        elseif ($db->inTransaction()) $db->rollBack();
        db_row_cache_clear();
        throw $e;
    }
}

// --- 4. 通用工具 ---
function h(string|int|float|bool|null $s): string { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
function now(): int { return time(); }

function cut(string $v, int $max): string
{
    $v = trim($v);
    return mb_strlen($v) > $max ? mb_substr($v, 0, $max) . '…' : $v;
}

function human_time(int $ts): string
{
    $diff = time() - $ts;
    if ($diff < 60) return '刚刚';
    if ($diff < 3600) return floor($diff / 60) . ' 分钟前';
    if ($diff < 86400) return floor($diff / 3600) . ' 小时前';
    if ($diff < 2592000) return floor($diff / 86400) . ' 天前';
    return date('Y-m-d', $ts);
}

// 依据种子（邮箱/昵称/IP）确定性生成 identicon 风格 SVG 头像，返回 data URI。
// 零依赖、不请求外部服务：同一 seed 永远得到同一头像，5x5 网格左右镜像对称。
function avatar_svg(string $seed, int $size = 64): string
{
    $seed = strtolower(trim($seed));
    if ($seed === '') $seed = 'mono';
    $size = max(16, min(256, $size));
    $hash = hash('sha256', $seed);
    $hue = hexdec(substr($hash, 0, 3)) % 360;
    $hue2 = ($hue + 32) % 360;
    $bg = sprintf('hsl(%d,52%%,95%%)', $hue);
    $fg = sprintf('hsl(%d,58%%,50%%)', $hue);
    $fg2 = sprintf('hsl(%d,58%%,62%%)', $hue2);
    $grid = 5;
    $cell = $size / $grid;
    $r = round($cell * 0.24, 2);
    $cells = '';
    for ($row = 0; $row < $grid; $row++) {
        for ($col = 0; $col < 3; $col++) {
            $bit = hexdec($hash[$row * 3 + $col]);
            if ($bit < 7) continue;
            $fill = ($bit % 2 === 0) ? $fg : $fg2;
            $y = round($row * $cell, 2);
            foreach ([$col, $grid - 1 - $col] as $c) {
                if ($c < $col) continue; // 仅镜像一次（中心列不重复）
                $cells .= '<rect x="' . round($c * $cell, 2) . '" y="' . $y . '" width="' . round($cell, 2) . '" height="' . round($cell, 2) . '" rx="' . $r . '" fill="' . $fill . '"/>';
            }
        }
    }
    return '<svg xmlns="http://www.w3.org/2000/svg" width="' . $size . '" height="' . $size . '" viewBox="0 0 ' . $size . ' ' . $size . '">'
        . '<rect width="' . $size . '" height="' . $size . '" fill="' . $bg . '"/>' . $cells . '</svg>';
}

function avatar_url(string $seed, int $size = 64): string
{
    return 'data:image/svg+xml,' . rawurlencode(avatar_svg($seed, $size));
}

// 自定义头像：app_users.avatar 列存扩展名（空串=默认 identicon），文件落盘 DATA_DIR/avatars/avatar-<id>.<ext>。
function avatar_dir(): string { return DATA_DIR . '/avatars'; }
function avatar_file(int $uid, string $ext): string { return avatar_dir() . '/avatar-' . $uid . '.' . $ext; }
function avatar_mime(string $ext): string { return ['png' => 'image/png', 'jpg' => 'image/jpeg', 'gif' => 'image/gif', 'webp' => 'image/webp'][$ext] ?? ''; }

// 用户头像 URL：有自定义头像走输出路由，否则回退种子 identicon。
function user_avatar_url(?array $user, int $size = 64): string
{
    $ext = $user ? (string)($user['avatar'] ?? '') : '';
    if ($ext !== '' && avatar_mime($ext) !== '' && is_file(avatar_file((int)$user['id'], $ext))) return route_url('avatar', ['id' => (int)$user['id']]);
    return avatar_url($user && (string)($user['email'] ?? '') !== '' ? (string)$user['email'] : (string)($user['nickname'] ?? 'mono'), $size);
}

// 头像输出路由：Content-Type 白名单映射 + 浏览器缓存，不暴露真实文件路径。
function avatar_route(): void
{
    $u = row('app_users', 'id', req_id());
    $ext = (string)($u['avatar'] ?? '');
    $mime = avatar_mime($ext);
    $file = $u && $mime !== '' ? avatar_file((int)$u['id'], $ext) : '';
    if (!$u || $file === '' || !is_file($file)) err('头像不存在', 404);
    header('Content-Type: ' . $mime);
    header('Content-Length: ' . (string)filesize($file));
    header('Cache-Control: public, max-age=86400');
    readfile($file);
    exit;
}

function slugify(string $text): string
{
    $text = strtolower(trim($text));
    $text = preg_replace('/[^a-z0-9]+/u', '-', $text) ?? '';
    return trim($text, '-') ?: '';
}


// --- 5. Cookie / 认证 / CSRF ---
function auth_cookie_secure(): bool
{
    return (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || (string)($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https';
}
function app_cookie(string $name, string $value, int $expires, bool $httponly = true): void
{
    setcookie($name, $value, ['expires' => $expires, 'path' => '/', 'secure' => auth_cookie_secure(), 'httponly' => $httponly, 'samesite' => 'Lax']);
}
function auth_cookie_clear(): void { app_cookie(AUTH_COOKIE_NAME, '', time() - 3600); unset($_COOKIE[AUTH_COOKIE_NAME]); }
function csrf_cookie_clear(): void { app_cookie(CSRF_COOKIE_NAME, '', time() - 3600); unset($_COOKIE[CSRF_COOKIE_NAME]); }

function auth_cookie_set(int $user_id, string $password_hash): void
{
    $expire = time() + COOKIE_TTL;
    $signature = hash_hmac('sha256', $user_id . '|' . $expire, $password_hash);
    app_cookie(AUTH_COOKIE_NAME, $user_id . '.' . $expire . '.' . $signature, $expire);
}
function auth_cookie_parts(): ?array
{
    $value = (string)($_COOKIE[AUTH_COOKIE_NAME] ?? '');
    if (!preg_match('/^(\d+)\.(\d+)\.([a-f0-9]{64})$/D', $value, $m)) return null;
    $id = (int)$m[1]; $expire = (int)$m[2];
    return $id > 0 && $expire > 0 ? ['id' => $id, 'expire' => $expire, 'signature' => $m[3]] : null;
}
function csrf_token(): string
{
    static $token = null;
    if ($token !== null) return $token;
    $token = (string)($_COOKIE[CSRF_COOKIE_NAME] ?? '');
    if (!preg_match('/^[a-f0-9]{64}$/D', $token)) {
        $token = bin2hex(random_bytes(32));
        app_cookie(CSRF_COOKIE_NAME, $token, time() + COOKIE_TTL, false);
        $_COOKIE[CSRF_COOKIE_NAME] = $token;
    }
    return $token;
}

// 当前登录用户（无状态 HMAC Cookie 认证，请求级缓存）。
function me(): ?array
{
    if (array_key_exists('__me_cache', $GLOBALS)) return is_array($GLOBALS['__me_cache']) ? $GLOBALS['__me_cache'] : null;
    $parts = auth_cookie_parts();
    if (!$parts || $parts['expire'] < time()) { if ($parts) auth_cookie_clear(); return $GLOBALS['__me_cache'] = null; }
    $u = row('app_users', 'id', $parts['id']);
    $expected = $u ? hash_hmac('sha256', $parts['id'] . '|' . $parts['expire'], (string)$u['password']) : '';
    if (!$u || !hash_equals($expected, $parts['signature'])) { clear_auth_cookie(); return $GLOBALS['__me_cache'] = null; }
    $GLOBALS['__request_uid'] = (int)$u['id'];
    return $GLOBALS['__me_cache'] = $u;
}
function uid(): int
{
    if (array_key_exists('__request_uid', $GLOBALS)) return (int)$GLOBALS['__request_uid'];
    $u = me();
    return $u ? (int)$u['id'] : 0;
}
function is_admin(): bool { $u = me(); return $u && (int)($u['is_admin'] ?? 0) === 1; }
function clear_auth_cookie(): void { auth_cookie_clear(); csrf_cookie_clear(); $GLOBALS['__request_uid'] = 0; $GLOBALS['__me_cache'] = null; }
function start_login(int $user_id): void
{
    $user = row('app_users', 'id', $user_id) ?: err('用户不存在');
    csrf_cookie_clear();
    auth_cookie_set($user_id, (string)$user['password']);
    $GLOBALS['__request_uid'] = $user_id;
    unset($GLOBALS['__me_cache']);
}
function need_login(): void { if (!me()) go(route_url('login')); }
function need_admin(): void { need_login(); if (!is_admin()) err('无权限访问', 403); }

function is_post_request(): bool { return ($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST'; }
function ajax_request(): bool { return ($_SERVER['HTTP_X_REQUESTED_WITH'] ?? '') === 'XMLHttpRequest'; }
function require_post(): void { if (!is_post_request()) err('非法请求', 400); }

// 全站 POST 请求统一 CSRF 校验（可被 request.csrf_exempt Hook 豁免）。
function check(): void
{
    if (uid()) me();
    if (!is_post_request()) return;
    $action = (string)($_GET['a'] ?? '');
    if (hook('request.csrf_exempt', false, ['action' => $action]) === true) return;
    if (!hash_equals(csrf_token(), (string)($_POST['_csrf'] ?? ''))) err('请求已过期，请重试');
}
function form_token(): string { return '<input type="hidden" name="_csrf" value="' . h(csrf_token()) . '">'; }
function set_flash(string $message, string $type = 'ok'): void { app_cookie('__flash', json_encode(['m' => $message, 't' => $type], JSON_UNESCAPED_UNICODE), time() + 60, true); }

// --- 6. 站点设置 ---
function default_settings(): array
{
    return [
        'site_name' => 'Mono',
        'site_description' => '一个简洁优雅的个人博客',
        'site_keywords' => '',
        'posts_per_page' => '10',
        'excerpt_length' => '160',
        'allow_comment' => '1',
        'pretty_url' => '0',
        'site_favicon' => '',
        'site_logo' => '',
    ];
}
function settings_cache(): array
{
    return $GLOBALS['__settings_cache'] ??= array_merge(
        default_settings(),
        array_column(q('SELECT name,value FROM app_settings')->fetchAll(), 'value', 'name')
    );
}
function setting(string $key, string $default = ''): string
{
    $s = settings_cache();
    return (string)($s[$key] ?? $default);
}
function save_settings_values(array $values): void
{
    $stmt = db()->prepare(app_db_upsert_sql(db_driver(), 'app_settings', ['name', 'value'], ['name']));
    foreach ($values as $name => $value) $stmt->execute([(string)$name, (string)$value]);
    db_row_cache_clear();
    if (is_array($GLOBALS['__settings_cache'] ?? null)) {
        foreach ($values as $name => $value) $GLOBALS['__settings_cache'][(string)$name] = (string)$value;
    }
    foreach (array_keys($values) as $name) {
        if (str_starts_with((string)$name, 'plugin_') || (string)$name === 'cache_plugins') { plugin_runtime_cache_reset(); break; }
    }
}

// 站点图标（favicon / 站点 Logo）：文件落盘 DATA_DIR/site/<kind>.<ext>，设置项 site_<kind> 存扩展名（空=未设置）。
function site_icon_dir(): string { return DATA_DIR . '/site'; }
function site_icon_file(string $kind, string $ext): string { return site_icon_dir() . '/' . $kind . '.' . $ext; }
function site_icon_mime(string $ext): string { return ['png' => 'image/png', 'jpg' => 'image/jpeg', 'gif' => 'image/gif', 'webp' => 'image/webp', 'ico' => 'image/vnd.microsoft.icon'][$ext] ?? ''; }
// 当前生效扩展名：设置值有效且文件存在才算已设置。
function site_icon_ext(string $kind): string
{
    $ext = (string)setting('site_' . $kind, '');
    return $ext !== '' && site_icon_mime($ext) !== '' && is_file(site_icon_file($kind, $ext)) ? $ext : '';
}
// 站点图标 URL：未设置返回空串（调用方回退默认展示）；带 mtime 指纹，换图立即刷新浏览器缓存。
function site_icon_url(string $kind): string
{
    $ext = site_icon_ext($kind);
    if ($ext === '') return '';
    return append_url_query(route_url('site_icon', ['f' => $kind]), ['v' => (string)filemtime(site_icon_file($kind, $ext))]);
}
// 站点图标输出路由：?a=site_icon&f=favicon|logo（伪静态 /site_icon?f=...），不暴露真实路径。
function site_icon_route(): void
{
    $kind = (string)($_GET['f'] ?? '');
    if (!in_array($kind, ['favicon', 'logo'], true)) err('图标不存在', 404);
    $ext = site_icon_ext($kind);
    if ($ext === '') err('图标不存在', 404);
    $file = site_icon_file($kind, $ext);
    header('Content-Type: ' . site_icon_mime($ext));
    header('Content-Length: ' . (string)filesize($file));
    header('Cache-Control: public, max-age=86400');
    readfile($file);
    exit;
}

// --- 7. 插件运行时与 Hook 管道 ---
function plugin_id_valid(string $id): bool { return preg_match('/^[a-z0-9][a-z0-9_-]{0,63}$/', $id) === 1; }
function plugin_runtime_cache_reset(): void { unset($GLOBALS['__hook_registry']); }
function plugin_json_decode(mixed $json, ?array $fallback = []): ?array
{
    if (is_array($json)) return $json;
    $value = json_decode((string)$json, true);
    return is_array($value) ? $value : $fallback;
}
function plugin_json_encode(array $value): string
{
    return json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
}
function plugin_load(array $plugin): void
{
    $file = (string)($plugin['file'] ?? '');
    if ($file === '' || !is_file($file)) return;
    if (array_key_exists($file, $GLOBALS['__plugin_raw'] ?? [])) return;
    $GLOBALS['__plugin_raw'][$file] = include $file;
}
function plugin_callback_exists(mixed $callback): bool { return is_string($callback) && $callback !== '' && function_exists($callback); }
function plugin_call(array $plugin, callable $callback): mixed
{
    try { plugin_load($plugin); return $callback(); }
    catch (Throwable $e) { Plugin::plugin_disable_after_exception((string)($plugin['id'] ?? ''), $e); throw $e; }
}

// 已启用插件（含 manifest 展开），请求级静态缓存，来源为持久化的运行时缓存行。
function plugins(bool $refresh = false): array
{
    static $plugins = null;
    if (!$refresh && $plugins !== null) return $plugins;
    $plugins = [];
    foreach (Plugin::plugin_runtime_cache_rows($refresh) as $p) {
        $p['file'] = APP_ROOT . '/' . (string)$p['file'];
        $p['enabled'] = true;
        $plugins[(string)$p['id']] = $p;
    }
    plugin_runtime_cache_reset();
    return $plugins;
}
function plugin_enabled(array $plugin): bool { return !empty($plugin['enabled']); }
function plugin_config(string $id, array $defaults = []): array
{
    if (!plugin_id_valid($id)) return $defaults;
    $plugin = plugins()[$id] ?? null;
    if ($plugin) return array_merge($defaults, (array)($plugin['config'] ?? []));
    $row = one('SELECT config_json FROM app_plugins WHERE id=?', [$id]);
    return array_merge($defaults, $row ? plugin_json_decode($row['config_json'] ?? '') ?? [] : []);
}
function plugin_save_config(string $id, array $config): void
{
    if (!plugin_id_valid($id)) err('插件不存在');
    Plugin::plugin_update_row($id, ['config_json' => $config]);
    plugins(true);
}

// 展示位置（entries）定义：控制插件在特定 Hook 是否显示，后台可开关。
function plugin_entry_definitions(): array
{
    return [
        'nav_links' => ['hook' => 'nav.menu_links', 'label' => '顶部导航'],
        'sidebar_cards' => ['hook' => 'sidebar.stack', 'label' => '侧栏卡片'],
        'post_actions' => ['hook' => 'post.actions', 'label' => '文章操作'],
        'admin_tabs' => ['hook' => 'admin.tabs', 'label' => '后台标签'],
    ];
}
function plugin_entry_hook_name(string $entry): string { return (string)(plugin_entry_definitions()[$entry]['hook'] ?? ''); }
function plugin_uses_entry(array $plugin, string $entry): bool
{
    $hook = plugin_entry_hook_name($entry);
    return $hook !== '' && isset($plugin['hooks'][$hook]);
}
function plugin_entry_enabled(array $plugin, string $entry): bool
{
    if (!plugin_uses_entry($plugin, $entry)) return false;
    return !array_key_exists($entry, (array)($plugin['entries'] ?? [])) || !empty($plugin['entries'][$entry]);
}

function hook_registry(): array
{
    if (is_array($GLOBALS['__hook_registry'] ?? null)) return $GLOBALS['__hook_registry'];
    $registry = [];
    foreach (plugins() as $plugin) {
        if (!plugin_enabled($plugin)) continue;
        foreach ((array)($plugin['hooks'] ?? []) as $name => $fn) {
            foreach (plugin_entry_definitions() as $entry => $def) {
                if ($name === $def['hook'] && !plugin_entry_enabled($plugin, $entry)) continue 2;
            }
            $registry[$name][] = ['plugin' => $plugin, 'fn' => $fn];
        }
    }
    return $GLOBALS['__hook_registry'] = $registry;
}

// Hook 管道：扩展返回新值以修改数据，返回 null 表示不修改。
function hook(string $name, mixed $value = null, array $ctx = []): mixed
{
    $registry = $GLOBALS['__hook_registry'] ?? hook_registry();
    $entries = $registry[$name] ?? null;
    if (!$entries) return $value;
    foreach ($entries as $entry) {
        $fn = $entry['fn'];
        $next = plugin_call($entry['plugin'], fn(): mixed => plugin_callback_exists($fn) ? $fn($value, $ctx) : null);
        if ($next !== null) $value = $next;
    }
    return $value;
}
function fire(string $name, array $ctx = []): void { hook($name, null, $ctx); }

// 插件路由分发：命中并已处理返回 true。
function plugin_route(string $action): bool
{
    foreach (plugins() as $plugin) {
        if (!plugin_enabled($plugin)) continue;
        $fn = $plugin['routes'][$action] ?? null;
        if ($fn === null) continue;
        $handled = plugin_call($plugin, function () use ($fn, $plugin): bool {
            if (!plugin_callback_exists($fn)) return false;
            $fn($plugin);
            return true;
        });
        if ($handled) return true;
    }
    return false;
}


// --- 8. URL 与路由 ---
function app_url(string $path = ''): string
{
    $path = ltrim($path, '/');
    $dir = rtrim(str_replace('\\', '/', dirname((string)($_SERVER['SCRIPT_NAME'] ?? '/index.php'))), '/');
    $base = ($dir === '' || $dir === '.') ? '' : $dir;
    if ($path === '') return $base === '' ? '/' : $base . '/';
    return $base . '/' . $path;
}
function append_url_query(string $url, array $params): string
{
    $query = [];
    foreach ($params as $k => $v) { if ($v === null || $v === '') continue; $query[$k] = (string)$v; }
    if (!$query) return $url;
    return $url . (str_contains($url, '?') ? '&' : '?') . http_build_query($query, '', '&', PHP_QUERY_RFC3986);
}
function index_url(array $params = []): string { return append_url_query(app_url('index.php'), $params); }
function admin_url(array $params = []): string { return route_url('admin', $params); }

// 统一路由 URL 生成：支持 ?a=action 与伪静态两种模式。
function route_url(string $a = 'home', array $params = []): string
{
    if (setting('pretty_url', '0') !== '1') return $a === 'home' ? index_url($params) : index_url(['a' => $a] + $params);
    if ($a === 'home') return $params ? append_url_query(app_url(''), $params) : app_url();
    $params = ['a' => $a] + $params;
    $segments = [];
    if (isset($params['a']) && $params['a'] !== '') { $segments[] = rawurlencode((string)$params['a']); unset($params['a']); }
    if (isset($params['id']) && ctype_digit((string)$params['id'])) { $segments[] = rawurlencode((string)$params['id']); unset($params['id']); }
    elseif ($a === 'page' && isset($params['slug']) && (string)$params['slug'] !== '') { $segments[] = rawurlencode((string)$params['slug']); unset($params['slug']); }
    return append_url_query(app_url(implode('/', $segments)), $params);
}
function asset_url(string $file): string { return app_url($file); }

// 解析伪静态路径，回填 $_GET['a'] 与 $_GET['id']。
function parse_path_route(): void
{
    $path = (string)(parse_url((string)($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH) ?? '');
    $script = str_replace('\\', '/', (string)($_SERVER['SCRIPT_NAME'] ?? '/index.php'));
    $base = rtrim(str_replace('\\', '/', dirname($script)), '/');
    if ($base !== '' && $base !== '.' && str_starts_with($path, $base . '/')) $path = substr($path, strlen($base));
    $path = trim($path, '/');
    if ($path === '' || $path === basename($script)) return;
    $segments = array_values(array_filter(explode('/', $path), 'strlen'));
    if (isset($segments[0]) && $segments[0] !== 'a' && !array_key_exists('a', $_GET)) $_GET['a'] = rawurldecode($segments[0]);
    if (isset($segments[1]) && !array_key_exists('id', $_GET)) {
        if (($segments[0] ?? '') === 'page') $_GET['slug'] = rawurldecode($segments[1]); else $_GET['id'] = rawurldecode($segments[1]);
    }
}

// --- 9. 请求输入与跳转 ---
function post(string $k, int $max = 0): string
{
    $v = trim((string)($_POST[$k] ?? ''));
    return $max > 0 ? mb_substr($v, 0, $max) : $v;
}
function req_id(string $k = 'id'): int { return (int)($_GET[$k] ?? 0); }
function go(string $u): never { header('Location: ' . $u); exit; }
function json_response(array $data): never
{
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE);
    exit;
}
function err(string $message, int $status = 200): never
{
    if (ajax_request()) json_response(['ok' => 0, 'message' => $message]);
    http_response_code($status);
    if (!db_schema_ready()) {
        echo '<!doctype html><meta charset="utf-8"><title>Mono</title><link rel="stylesheet" href="' . h(asset_url('app/assets/index.css')) . '"><div class="install-wrap"><div class="card error-box"><h2>出错了</h2><p>' . h($message) . '</p></div></div>';
        exit;
    }
    page('出错了', '<div class="install-wrap"><div class="card error-box"><h2>' . h($message) . '</h2><p><a class="btn ghost" href="' . h(route_url('home')) . '">返回首页</a></p></div></div>', [], true);
    exit;
}

// --- 10. 表单助手 ---
function form_field_caption(string $label, string $help = ''): string
{
    return '<span class="field-caption">' . h($label) . ($help !== '' ? '<span class="field-help">' . h($help) . '</span>' : '') . '</span>';
}
function input(string $label, string $name, mixed $value = '', string $type = 'text', bool $required = false, string $help = ''): string
{
    return '<label class="grid">' . form_field_caption($label, $help) . '<input name="' . h($name) . '" type="' . h($type) . '" value="' . h($value) . '"' . ($required ? ' required' : '') . '></label>';
}
function textarea(string $label, string $name, mixed $value = '', bool $required = false, string $help = '', string $attr = ''): string
{
    return '<label class="grid">' . form_field_caption($label, $help) . '<textarea name="' . h($name) . '"' . ($required ? ' required' : '') . ' ' . $attr . '>' . h($value) . '</textarea></label>';
}
function checkbox(string $label, string $name, bool $checked = false, string $help = ''): string
{
    return '<label class="grid checkbox-row"><input type="hidden" name="' . h($name) . '" value="0"><input type="checkbox" name="' . h($name) . '" value="1"' . ($checked ? ' checked' : '') . '><span>' . h($label) . ($help !== '' ? ' <span class="field-help">' . h($help) . '</span>' : '') . '</span></label>';
}
function select_input(string $label, string $name, mixed $value, array $options, string $help = ''): string
{
    $html = '<label class="grid">' . form_field_caption($label, $help) . '<select name="' . h($name) . '">';
    foreach ($options as $k => $text) $html .= '<option value="' . h((string)$k) . '"' . ((string)$k === (string)$value ? ' selected' : '') . '>' . h((string)$text) . '</option>';
    return $html . '</select></label>';
}
// 渲染带 CSRF 的 POST 操作表单（用于删除等状态变更）。
function post_action_form(string $action, string $label, array $fields = [], string $class = 'btn sm ghost', string $confirm = ''): string
{
    $hidden = form_token();
    foreach ($fields as $k => $v) $hidden .= '<input type="hidden" name="' . h($k) . '" value="' . h((string)$v) . '">';
    return '<form method="post" action="' . h($action) . '" style="display:inline"' . ($confirm !== '' ? ' data-confirm="' . h($confirm) . '"' : '') . '>' . $hidden . '<button type="submit" class="' . h($class) . '">' . h($label) . '</button></form>';
}

// --- 11. Markdown 渲染（可被 Hook 扩展）---
// 轻量服务端代码高亮：按语言族用有序正则分词，输出 tok-* span（零依赖、无外部库）。
function code_token_patterns(string $lang): array
{
    $str_dq = '"[^"\n]*"';
    $str_sq = "'[^'\n]*'";
    $str_both = $str_dq . '|' . $str_sq;
    $num = '\b0[xXbB][0-9a-fA-F_]+\b|\b\d+(?:\.\d+)?\b';
    $type = '\b[A-Z][A-Za-z0-9_]*\b';
    $fn = '\b[a-z_][A-Za-z0-9_]*(?=\s*\()';
    switch ($lang) {
        case 'php':
            return [
                ['\/\/[^\n]*|#[^\n]*|\/\*.*?\*\/', 'com'],
                [$str_both, 'str'],
                ['\$[A-Za-z_]\w*', 'var'],
                [$num, 'num'],
                ['\b(?:abstract|array|as|break|callable|case|catch|class|clone|const|continue|declare|default|do|echo|else|elseif|empty|enum|extends|final|finally|fn|for|foreach|function|global|goto|if|implements|include|instanceof|insteadof|interface|isset|list|match|namespace|new|print|private|protected|public|readonly|require|return|static|switch|throw|trait|try|unset|use|var|while|yield|null|true|false)\b', 'kw'],
                [$type, 'type'],
                [$fn, 'fn'],
            ];
        case 'js': case 'javascript': case 'ts': case 'typescript': case 'jsx': case 'tsx':
            return [
                ['\/\/[^\n]*|\/\*.*?\*\/', 'com'],
                [$str_both . '|`[^`]*`', 'str'],
                [$num, 'num'],
                ['\b(?:async|await|break|case|catch|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally|for|from|function|get|if|implements|import|in|instanceof|interface|let|new|of|package|private|protected|public|return|set|static|super|switch|this|throw|try|type|typeof|var|void|while|with|yield|null|true|false|undefined)\b', 'kw'],
                [$type, 'type'],
                [$fn, 'fn'],
            ];
        case 'c': case 'cpp': case 'java': case 'cs': case 'go': case 'rust': case 'kotlin': case 'swift':
            return [
                ['\/\/[^\n]*|\/\*.*?\*\/', 'com'],
                [$str_both, 'str'],
                [$num, 'num'],
                ['\b(?:auto|bool|break|case|char|class|const|continue|default|do|double|else|enum|extern|float|for|func|fun|goto|if|int|interface|long|map|new|package|public|private|protected|return|short|signed|sizeof|static|struct|switch|typedef|union|unsigned|use|var|void|volatile|while|null|true|false|nil|None)\b', 'kw'],
                [$type, 'type'],
                [$fn, 'fn'],
            ];
        case 'css': case 'scss': case 'less':
            return [
                ['\/\*.*?\*\/', 'com'],
                [$str_both, 'str'],
                ['@[\w-]+', 'kw'],
                ['[\w-]+(?=\s*:)', 'attr'],
                ['#[0-9a-fA-F]{3,8}\b|\b\d+(?:\.\d+)?(?:px|em|rem|%|vh|vw|vmin|vmax|s|ms|fr)?\b', 'num'],
                ['\.[-\w]+', 'type'],
                ['::{1,2}[\w-]+', 'fn'],
            ];
        case 'html': case 'xml': case 'svg': case 'vue':
            return [
                ['<!--.*?-->', 'com'],
                ['<!.*?>', 'kw'],
                ['<\/?[a-zA-Z][\w:-]*|/?>', 'tag'],
                ['[\w:-]+(?=\s*=)', 'attr'],
                [$str_both, 'str'],
            ];
        case 'sql':
            return [
                ['--[^\n]*|\/\*.*?\*\/', 'com'],
                [$str_sq, 'str'],
                ['\b(?i:select|from|where|insert|into|values|update|set|delete|create|table|drop|alter|add|index|unique|primary|key|foreign|references|join|left|right|inner|outer|on|group|by|order|asc|desc|limit|offset|having|distinct|as|and|or|not|null|is|in|like|ilike|between|exists|union|all|count|sum|avg|min|max|begin|commit|rollback)\b', 'kw'],
                [$num, 'num'],
                [$fn, 'fn'],
            ];
        case 'sh': case 'bash': case 'shell': case 'zsh':
            return [
                ['#[^\n]*', 'com'],
                [$str_both, 'str'],
                ['\$\{?[#@*?0-9A-Za-z_]+\}?', 'var'],
                ['\b(?:if|then|else|elif|fi|for|while|until|do|done|case|esac|function|return|exit|export|local|source|in)\b', 'kw'],
                ['-{1,2}[\w-]+', 'attr'],
                [$num, 'num'],
            ];
        case 'json':
            return [
                ['"[^"\n]*"(?=\s*:)', 'attr'],
                ['"[^"\n]*"', 'str'],
                ['\b(?:true|false|null)\b', 'kw'],
                ['-?\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b', 'num'],
            ];
        case 'py': case 'python':
            return [
                ['#[^\n]*', 'com'],
                ['"""[\s\S]*?"""|' . $str_both, 'str'],
                ['\b(?:def|class|return|if|elif|else|for|while|import|from|as|with|try|except|finally|raise|pass|break|continue|lambda|yield|global|nonlocal|assert|del|in|is|not|and|or|None|True|False|async|await|self)\b', 'kw'],
                [$type, 'type'],
                [$fn, 'fn'],
                [$num, 'num'],
            ];
        case 'yaml': case 'yml':
            return [
                ['#[^\n]*', 'com'],
                ['(?m)^[\s-]*[\w.-]+(?=\s*:)', 'attr'],
                [$str_both, 'str'],
                ['\b(?:true|false|null|yes|no|on|off)\b', 'kw'],
                [$num, 'num'],
            ];
        default:
            return [];
    }
}

// 将原始代码按语言分词并转义输出；未知语言仅转义不高亮。
function code_highlight(string $code, string $lang): string
{
    $pats = code_token_patterns($lang);
    if (!$pats) return h($code);
    $alt = [];
    foreach ($pats as $p) $alt[] = '(' . $p[0] . ')';
    $regex = '/' . implode('|', $alt) . '/s';
    $out = '';
    $last = 0;
    if (preg_match_all($regex, $code, $m, PREG_OFFSET_CAPTURE | PREG_SET_ORDER) > 0) {
        foreach ($m as $set) {
            $text = $set[0][0];
            $offset = $set[0][1];
            if ($offset > $last) $out .= h(substr($code, $last, $offset - $last));
            $cls = 'plain';
            for ($i = 1; $i < count($set); $i++) {
                if (($set[$i][1] ?? -1) !== -1) { $cls = $pats[$i - 1][1]; break; }
            }
            $out .= '<span class="tok-' . $cls . '">' . h($text) . '</span>';
            $last = $offset + strlen($text);
        }
    }
    return $out . h(substr($code, $last));
}

function markdown_html(string $text): string
{
    $text = (string)hook('markdown.render', $text, []);
    // 提取代码块：服务端高亮 + 语言标签/复制按钮外壳，避免内部被其它规则破坏。
    $blocks = [];
    $text = preg_replace_callback('/```(\w*)\n(.*?)```/s', function ($m) use (&$blocks) {
        $lang = strtolower($m[1]);
        $raw = rtrim($m[2], "\n");
        $label = $lang !== '' ? $lang : 'text';
        $blocks[] = '<div class="codeblock" data-lang="' . h($label) . '">'
            . '<div class="codeblock-bar"><span class="codeblock-lang">' . h($label) . '</span>'
            . '<button type="button" class="codeblock-copy">复制</button></div>'
            . '<pre><code' . ($lang !== '' ? ' class="language-' . h($lang) . '"' : '') . '>' . code_highlight($raw, $lang) . '</code></pre></div>';
        return "\x00BLOCK" . (count($blocks) - 1) . "\x00";
    }, $text) ?? $text;

    $text = h($text);
    // 标题
    $text = preg_replace('/^######\s+(.*$)/m', '<h6>$1</h6>', $text) ?? $text;
    $text = preg_replace('/^#####\s+(.*$)/m', '<h5>$1</h5>', $text) ?? $text;
    $text = preg_replace('/^####\s+(.*$)/m', '<h4>$1</h4>', $text) ?? $text;
    $text = preg_replace('/^###\s+(.*$)/m', '<h3>$1</h3>', $text) ?? $text;
    $text = preg_replace('/^##\s+(.*$)/m', '<h2>$1</h2>', $text) ?? $text;
    $text = preg_replace('/^#\s+(.*$)/m', '<h1>$1</h1>', $text) ?? $text;
    // 分割线
    $text = preg_replace('/^(\-{3,}|\*{3,})$/m', '<hr>', $text) ?? $text;
    // 引用
    $text = preg_replace('/^&gt;\s+(.*$)/m', '<blockquote>$1</blockquote>', $text) ?? $text;
    // 图片与链接
    $text = preg_replace('/!\[(.*?)\]\((https?:\/\/[^\s)]+)\)/', '<img src="$2" alt="$1">', $text) ?? $text;
    $text = preg_replace('/\[(.*?)\]\((https?:\/\/[^\s)]+)\)/', '<a href="$2" target="_blank" rel="noopener nofollow">$1</a>', $text) ?? $text;
    // 粗体、斜体、行内代码
    $text = preg_replace('/\*\*(.+?)\*\*/s', '<strong>$1</strong>', $text) ?? $text;
    $text = preg_replace('/(?<!\*)\*([^*\n]+?)\*(?!\*)/', '<em>$1</em>', $text) ?? $text;
    $text = preg_replace('/`([^`\n]+?)`/', '<code>$1</code>', $text) ?? $text;
    // 无序列表
    $text = preg_replace_callback('/(?:^|\n)((?:[-*]\s+.*\n?)+)/', function ($m) {
        $items = preg_split('/\n/', trim($m[1]));
        $li = '';
        foreach ($items as $it) { $it = preg_replace('/^[-*]\s+/', '', $it); $li .= '<li>' . $it . '</li>'; }
        return "\n<ul>$li</ul>";
    }, $text) ?? $text;
    // 段落与换行
    $text = nl2br($text);
    $text = preg_replace('/<br\s*\/?>\s*(<\/?(?:h[1-6]|ul|li|blockquote|pre|hr|img)[^>]*>)/', '$1', $text) ?? $text;
    // 还原代码块
    $text = preg_replace_callback('/\x00BLOCK(\d+)\x00/', fn($m) => $blocks[(int)$m[1]] ?? '', $text) ?? $text;

    return (string)hook('markdown.after', $text, []);
}


// --- 12. 插件资源合并标签 ---
function db_schema_ready(): bool { return is_file(INSTALL_LOCK_FILE); }

function plugin_assets_manifest(): array
{
    static $manifest;
    if (is_array($manifest)) return $manifest;
    if (setting('plugin_assets_dirty', '1') === '1' || !is_file(PLUGIN_CSS_FILE) || !is_file(PLUGIN_JS_FILE)) {
        try { return $manifest = Plugin::plugin_assets_rebuild(); }
        catch (Throwable $e) { return $manifest = []; }
    }
    return $manifest = [
        'css' => setting('plugin_assets_css_hash'), 'css_size' => (int)setting('plugin_assets_css_size'),
        'js' => setting('plugin_assets_js_hash'), 'js_size' => (int)setting('plugin_assets_js_size'),
    ];
}
function plugin_asset_tag(string $type): string
{
    $manifest = plugin_assets_manifest();
    if (!in_array($type, ['css', 'js'], true) || (int)($manifest[$type . '_size'] ?? 0) < 1) return '';
    $version = (string)($manifest[$type] ?? '');
    $file = 'app/assets/plugins.' . $type;
    if ($type === 'css') return '<link rel="stylesheet" href="' . h(asset_url($file)) . '?v=' . h($version) . '">';
    return '<script src="' . h(asset_url($file)) . '?v=' . h($version) . '" defer></script>';
}

// --- 13. 分页 ---
function paginate(int $total, int $page, int $size, callable $url_fn): string
{
    $pages = (int)ceil($total / max(1, $size));
    if ($pages <= 1) return '';
    $page = max(1, min($page, $pages));
    $html = '<div class="pager">';
    if ($page > 1) $html .= '<a href="' . h($url_fn($page - 1)) . '">上一页</a>';
    $window = 2;
    $start = max(1, $page - $window); $end = min($pages, $page + $window);
    if ($start > 1) { $html .= '<a href="' . h($url_fn(1)) . '">1</a>'; if ($start > 2) $html .= '<span class="gap">…</span>'; }
    for ($i = $start; $i <= $end; $i++) {
        $html .= $i === $page ? '<span class="current">' . $i . '</span>' : '<a href="' . h($url_fn($i)) . '">' . $i . '</a>';
    }
    if ($end < $pages) { if ($end < $pages - 1) $html .= '<span class="gap">…</span>'; $html .= '<a href="' . h($url_fn($pages)) . '">' . $pages . '</a>'; }
    if ($page < $pages) $html .= '<a href="' . h($url_fn($page + 1)) . '">下一页</a>';
    return $html . '</div>';
}

// --- 14. 页面骨架渲染 ---
// 浏览器标签页图标：自定义 favicon 优先，未设置回退内置 index.svg。
function favicon_link_html(): string
{
    $ext = site_icon_ext('favicon');
    if ($ext !== '') return '<link rel="icon" type="' . h(site_icon_mime($ext)) . '" href="' . h(site_icon_url('favicon')) . '">';
    return '<link rel="icon" type="image/svg+xml" href="' . h(asset_url('app/assets/index.svg')) . '">';
}
function page_head_html(string $page_title, string $meta, string $head_extra = ''): string
{
    return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">'
        . '<meta name="viewport" content="width=device-width,initial-scale=1">'
        // 主题偏好在首屏前应用：手动偏好 > 服务端默认（.dark）> 系统偏好；系统变化实时跟随。
        . '<script>(function(){var d=document.documentElement,s=null;try{s=localStorage.getItem("mono-theme")}catch(e){}var dark=s?s==="dark":(d.classList.contains("dark")||window.matchMedia("(prefers-color-scheme: dark)").matches);d.classList.toggle("dark",dark);var mq=window.matchMedia("(prefers-color-scheme: dark)"),f=function(e){var c=null;try{c=localStorage.getItem("mono-theme")}catch(e2){}if(!c)d.classList.toggle("dark",e.matches)};mq.addEventListener?mq.addEventListener("change",f):mq.addListener(f);})();</script>'
        . $meta
        . '<title>' . h($page_title) . '</title>'
        . favicon_link_html()
        . '<link rel="stylesheet" href="' . h(asset_url('app/assets/index.css')) . '?v=' . h(APP_VERSION) . '">'
        . plugin_asset_tag('css') . $head_extra . '</head><body>';
}

function nav_menu_links(): array
{
    $links = [
        ['url' => route_url('home'), 'text' => '首页'],
        ['url' => route_url('archive'), 'text' => '归档'],
    ];
    // 分类不在顶部导航展示（侧栏已有完整分类列表），避免分类多时挤爆导航。
    foreach (pages_cache() as $p) {
        $links[] = ['url' => route_url('page', ['slug' => (string)$p['slug']]), 'text' => (string)$p['title']];
    }
    // 插件可追加导航链接（每页一次，非循环）。
    foreach (hook('nav.menu_links', [], []) as $link) {
        if (is_array($link) && isset($link['url'], $link['text'])) $links[] = $link;
    }
    return $links;
}

function page_nav_html(string $site_name): string
{
    $active = (string)($_GET['a'] ?? 'home');
    // 品牌图标：自定义 Logo 优先，未设置回退站名首字母方块。
    $logo = site_icon_url('logo');
    $brand_icon = $logo !== ''
        ? '<img class="brand-logo" src="' . h($logo) . '" alt="">'
        : '<span class="brand-mark">' . h(mb_strtoupper(mb_substr($site_name !== '' ? $site_name : 'Mono', 0, 1, 'UTF-8'), 'UTF-8')) . '</span>';
    $html = '<div class="top"><div class="bar"><a class="brand" href="' . h(route_url('home')) . '">' . $brand_icon . h($site_name) . '</a>';
    $html .= '<nav class="nav" data-slot="nav.menu_links">';
    foreach (nav_menu_links() as $link) {
        $is_active = $link['url'] === route_url($active === 'home' ? 'home' : $active, $active === 'page' ? ['slug' => (string)($_GET['slug'] ?? '')] : []);
        $html .= '<a class="nav-link' . ($is_active ? ' active' : '') . '" href="' . h((string)$link['url']) . '">' . h((string)$link['text']) . '</a>';
    }
    $html .= '</nav><div class="bar-right" data-slot="top.bar.actions">';
    // 深浅色切换按钮：手动偏好写 localStorage，未手动时跟随服务端默认或系统。
    $html .= '<button class="icon-btn theme-toggle" type="button" aria-label="切换深浅色主题" title="切换深浅色主题">'
        . '<svg class="icon-moon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>'
        . '<svg class="icon-sun" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>'
        . '</button>';
    $html .= (string)hook('top.bar.actions', '', []);
    $me = me();
    if ($me) {
        // 登录态操作收进头像子菜单：写文章为主按钮高亮，「管理」原「后台」，退出置底；顶栏只留头像入口。
        $html .= '<div class="user-menu">'
            . '<button type="button" class="user-menu-btn" aria-haspopup="true" aria-expanded="false">'
            . '<img class="nav-avatar" src="' . h(user_avatar_url($me, 60)) . '" alt="">'
            . '<span class="nav-user">' . h((string)$me['nickname']) . '</span>'
            . '<svg class="user-menu-chevron" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>'
            . '</button>'
            . '<div class="user-menu-panel">'
            . '<div class="user-menu-head"><strong>' . h((string)$me['nickname']) . '</strong><span>' . h((string)$me['email']) . '</span></div>'
            . (is_admin()
                ? '<a class="user-menu-item primary" href="' . h(route_url('write')) . '">写文章</a>'
                . '<a class="user-menu-item" href="' . h(admin_url()) . '">管理</a>'
                . '<div class="user-menu-sep"></div>'
                : '')
            . '<a class="user-menu-item danger" href="' . h(route_url('logout')) . '">退出登录</a>'
            . '</div></div>';
    } else {
        $html .= '<a class="btn sm ghost" href="' . h(route_url('login')) . '">登录</a>';
    }
    return $html . '</div></div></div>';
}

function page_footer_html(array $flash): string
{
    $footer = (string)hook('page.footer', '', []);
    $year = date('Y');
    // 页脚署名固定为程序名 Mono，链接开源仓库（预留地址）；末尾附 RSS 订阅入口。
    $base = '<div class="footer" data-slot="page.footer">' . $footer
        . '<div>Powered by <a href="https://github.com/hzruo/mono" target="_blank" rel="noopener">Mono</a> · ' . $year
        . ' · <a href="' . h(route_url('rss')) . '" title="RSS 订阅">RSS</a></div></div>';
    $js = '<script>window.__pageFlash=' . json_encode($flash, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) . ';</script>'
        . '<script src="' . h(asset_url('app/assets/index.js')) . '?v=' . h(APP_VERSION) . '" defer></script>' . plugin_asset_tag('js');
    return $base . $js . '</body></html>';
}

// 双栏外壳：主内容 + 侧栏。
function shell_html(string $main, string $sidebar = ''): string
{
    if ($sidebar === '') return '<div class="wrap single"><div class="main" data-slot="page.before_render">' . $main . '</div></div>';
    return '<div class="wrap"><div class="main" data-slot="page.before_render">' . $main . '</div><aside class="sidebar" data-slot="sidebar.stack">' . $sidebar . '</aside></div>';
}

function page_template(array $data): string
{
    $html = hook('page.template.before', null, $data);
    if (!is_string($html)) {
        $html = page_head_html($data['page_title'], $data['meta'], $data['head_extra'])
            . page_nav_html($data['site_name'])
            . $data['header_html']
            . '<div class="page-body">' . $data['body'] . '</div>'
            . page_footer_html($data['flash']);
    }
    return (string)hook('page.template', $html, $data);
}

// 输出整页。$bare=true 时用于错误页（不含侧栏逻辑）。
function page(string $title, string $body, array $seo = [], bool $bare = false): void
{
    $settings = settings_cache();
    $body = (string)hook('page.before_render', $body, ['title' => $title]);
    $site_name = trim((string)$settings['site_name']) ?: 'Mono';
    $is_home = ($_GET['a'] ?? 'home') === 'home';
    $page_title = $is_home || $title === '' ? $site_name : $title . ' - ' . $site_name;
    $hook_seo = hook('page.seo', $seo, ['title' => $title, 'page_title' => $page_title]);
    if (is_array($hook_seo)) $seo = $hook_seo;
    $meta = '';
    $description = trim((string)($seo['description'] ?? ($settings['site_description'] ?? '')));
    if ($description !== '') $meta .= '<meta name="description" content="' . h($description) . '">';
    if ($is_home && trim((string)($settings['site_keywords'] ?? '')) !== '') $meta .= '<meta name="keywords" content="' . h($settings['site_keywords']) . '">';
    if (!empty($seo['canonical'])) $meta .= '<link rel="canonical" href="' . h((string)$seo['canonical']) . '">';
    $head_extra = (string)hook('page.head', '', ['title' => $title, 'page_title' => $page_title]);
    $flash_raw = trim((string)($_COOKIE['__flash'] ?? ''));
    $flash = json_decode($flash_raw, true);
    if (!is_array($flash) || !isset($flash['m'])) $flash = ['m' => $flash_raw, 't' => 'ok'];
    if ($flash_raw !== '' && !headers_sent()) app_cookie('__flash', '', time() - 3600);
    $header_html = (string)hook('page.header', '', ['title' => $title]);
    echo page_template(compact('title', 'body', 'seo', 'settings', 'site_name', 'page_title', 'is_home', 'meta', 'head_extra', 'header_html', 'flash'));
}

// --- 15. 侧栏组件（分类/标签/归档，整页一次查询，无 N+1）---
function categories_cache(): array
{
    return $GLOBALS['__categories_cache'] ??= all('SELECT * FROM app_categories ORDER BY sort ASC, id ASC');
}

// 已发布独立页面（导航与渲染共用，整页一次查询）。
function pages_cache(): array
{
    return $GLOBALS['__pages_cache'] ??= all('SELECT * FROM app_pages WHERE status=1 ORDER BY sort ASC, id ASC');
}
function category_by_id(int $id): ?array
{
    foreach (categories_cache() as $c) if ((int)$c['id'] === $id) return $c;
    return null;
}
function sidebar_default_html(): string
{
    $html = '';
    // 分类
    $cats = all('SELECT c.id,c.name,COUNT(p.id) AS cnt FROM app_categories c LEFT JOIN app_posts p ON p.category_id=c.id AND p.status=1 GROUP BY c.id ORDER BY c.sort ASC,c.id ASC');
    if ($cats) {
        $html .= '<div class="card"><div class="card-title">分类</div><ul class="side-list">';
        foreach ($cats as $c) $html .= '<li><a href="' . h(route_url('category', ['id' => (int)$c['id']])) . '">' . h($c['name']) . '</a><span class="count">' . (int)$c['cnt'] . '</span></li>';
        $html .= '</ul></div>';
    }
    // 标签
    $tags = all('SELECT t.id,t.name,COUNT(pt.post_id) AS cnt FROM app_tags t JOIN app_post_tags pt ON pt.tag_id=t.id JOIN app_posts p ON p.id=pt.post_id AND p.status=1 GROUP BY t.id ORDER BY cnt DESC LIMIT 30');
    if ($tags) {
        $html .= '<div class="card"><div class="card-title">标签</div><div class="tag-cloud">';
        foreach ($tags as $t) $html .= '<a class="tag" href="' . h(route_url('tag', ['id' => (int)$t['id']])) . '">' . h($t['name']) . ' <small>' . (int)$t['cnt'] . '</small></a>';
        $html .= '</div></div>';
    }
    // 归档（按月）
    $archives = post_archive_counts();
    if ($archives) {
        $html .= '<div class="card"><div class="card-title">归档</div><ul class="side-list">';
        foreach ($archives as $a) $html .= '<li><a href="' . h(route_url('archive', ['ym' => $a['ym']])) . '">' . h($a['label']) . '</a><span class="count">' . (int)$a['cnt'] . '</span></li>';
        $html .= '</ul></div>';
    }
    return $html;
}
function sidebar_html(): string
{
    return (string)hook('sidebar.stack', sidebar_default_html(), []);
}

// 按月归档统计：跨库使用各自的时间格式化函数（显式覆盖三驱动）。
function post_archive_counts(): array
{
    $expr = match (db_driver()) {
        'mysql' => "DATE_FORMAT(FROM_UNIXTIME(created_at),'%Y-%m')",
        'pgsql' => "to_char(to_timestamp(created_at),'YYYY-MM')",
        default => "strftime('%Y-%m',created_at,'unixepoch','localtime')",
    };
    $rows = all("SELECT $expr AS ym, COUNT(*) AS cnt FROM app_posts WHERE status=1 GROUP BY ym ORDER BY ym DESC LIMIT 24");
    $out = [];
    foreach ($rows as $r) {
        $ym = (string)$r['ym'];
        $out[] = ['ym' => $ym, 'label' => str_replace('-', ' 年 ', $ym) . ' 月', 'cnt' => (int)$r['cnt']];
    }
    return $out;
}


// --- 16. 文章数据与列表渲染 ---
function post_excerpt(string $content, ?int $max = null): string
{
    $max ??= max(20, (int)setting('excerpt_length', '160'));
    $plain = preg_replace('/```.*?```/s', ' ', $content) ?? $content;
    $plain = preg_replace('/[#>*`_\-\[\]()!]/', '', $plain) ?? $plain;
    $plain = trim(preg_replace('/\s+/', ' ', $plain) ?? '');
    return cut($plain, $max);
}

// 批量取回一组文章的标签，构建 post_id => tags 映射（避免列表 N+1）。
function posts_tags_map(array $post_ids): array
{
    $post_ids = array_values(array_unique(array_filter(array_map('intval', $post_ids))));
    if (!$post_ids) return [];
    $rows = all('SELECT pt.post_id,t.id,t.name FROM app_post_tags pt JOIN app_tags t ON t.id=pt.tag_id WHERE pt.post_id IN (' . sql_marks(count($post_ids)) . ')', $post_ids);
    $map = [];
    foreach ($rows as $r) $map[(int)$r['post_id']][] = ['id' => (int)$r['id'], 'name' => (string)$r['name']];
    return $map;
}

// 列表中的单篇文章 HTML。$tags 由整页预载传入，循环内零查询。
function post_list_row(array $p, array $tags = []): string
{
    $cat = (int)$p['category_id'] > 0 ? category_by_id((int)$p['category_id']) : null;
    $html = '<article class="post-item" data-slot="post.list.after_render" data-post-id="' . (int)$p['id'] . '">';
    $html .= '<h2 class="post-title"><a href="' . h(route_url('post', ['id' => (int)$p['id']])) . '">' . h($p['title']) . '</a></h2>';
    $html .= '<div class="post-meta"><span>' . h(date('Y-m-d', (int)$p['created_at'])) . '</span>';
    if ($cat) $html .= '<span>· <a href="' . h(route_url('category', ['id' => (int)$cat['id']])) . '">' . h($cat['name']) . '</a></span>';
    $html .= '<span>· ' . (int)$p['view_count'] . ' 阅读</span>';
    if ((int)$p['status'] !== 1) $html .= '<span class="badge draft">草稿</span>';
    $html .= '</div>';
    $html .= '<p class="post-excerpt">' . h(post_excerpt((string)$p['content'])) . '</p>';
    if ($tags) {
        $html .= '<div class="post-tags">';
        foreach ($tags as $t) $html .= '<a class="tag" href="' . h(route_url('tag', ['id' => (int)$t['id']])) . '">' . h($t['name']) . '</a>';
        $html .= '</div>';
    }
    $html .= (string)hook('post.list.after_render', '', ['post' => $p]);
    return $html . '</article>';
}

// 文章列表页通用渲染：$where/$params 决定数据源，整页批量预载标签。
function render_post_list(array $posts, int $total, int $page, callable $url_fn, string $empty_text = '还没有文章。'): string
{
    if (!$posts) return '<div class="card"><p style="color:var(--text-muted);margin:0">' . h($empty_text) . '</p></div>';
    $tags_map = posts_tags_map(array_column($posts, 'id'));
    $html = '<div class="card">';
    foreach ($posts as $p) $html .= post_list_row($p, $tags_map[(int)$p['id']] ?? []);
    $html .= '</div>';
    return $html . paginate($total, $page, (int)setting('posts_per_page', '10'), $url_fn);
}

function current_page(): int { return max(1, (int)($_GET['page'] ?? 1)); }

// 首页：已发布文章分页列表。
function home_page(): void
{
    $page = current_page();
    $size = max(1, (int)setting('posts_per_page', '10'));
    $offset = ($page - 1) * $size;
    $total = (int)val('SELECT COUNT(*) FROM app_posts WHERE status=1');
    $posts = all("SELECT * FROM app_posts WHERE status=1 ORDER BY created_at DESC, id DESC LIMIT $size OFFSET $offset");
    $body = render_post_list($posts, $total, $page, fn(int $p): string => route_url('home', ['page' => $p]), '博客还没有发布任何文章。');
    page('', shell_html($body, sidebar_html()));
}

// 分类页。
function category_page(): void
{
    $cat = category_by_id(req_id());
    if (!$cat) err('分类不存在', 404);
    $page = current_page();
    $size = max(1, (int)setting('posts_per_page', '10'));
    $offset = ($page - 1) * $size;
    $cid = (int)$cat['id'];
    $total = (int)val('SELECT COUNT(*) FROM app_posts WHERE status=1 AND category_id=?', [$cid]);
    $posts = all("SELECT * FROM app_posts WHERE status=1 AND category_id=? ORDER BY created_at DESC, id DESC LIMIT $size OFFSET $offset", [$cid]);
    $head = '<div class="card" style="padding:14px 20px;margin-bottom:16px"><strong>分类：' . h($cat['name']) . '</strong> <span class="badge">' . $total . ' 篇</span></div>';
    $body = $head . render_post_list($posts, $total, $page, fn(int $p): string => route_url('category', ['id' => $cid, 'page' => $p]));
    page($cat['name'], shell_html($body, sidebar_html()));
}

// 标签页。
function tag_page(): void
{
    $tag = row('app_tags', 'id', req_id());
    if (!$tag) err('标签不存在', 404);
    $page = current_page();
    $size = max(1, (int)setting('posts_per_page', '10'));
    $offset = ($page - 1) * $size;
    $tid = (int)$tag['id'];
    $total = (int)val('SELECT COUNT(*) FROM app_post_tags pt JOIN app_posts p ON p.id=pt.post_id WHERE pt.tag_id=? AND p.status=1', [$tid]);
    $posts = all("SELECT p.* FROM app_post_tags pt JOIN app_posts p ON p.id=pt.post_id WHERE pt.tag_id=? AND p.status=1 ORDER BY p.created_at DESC, p.id DESC LIMIT $size OFFSET $offset", [$tid]);
    $head = '<div class="card" style="padding:14px 20px;margin-bottom:16px"><strong>标签：' . h($tag['name']) . '</strong> <span class="badge">' . $total . ' 篇</span></div>';
    $body = $head . render_post_list($posts, $total, $page, fn(int $p): string => route_url('tag', ['id' => $tid, 'page' => $p]));
    page($tag['name'], shell_html($body, sidebar_html()));
}

// 归档页：全部或指定年月（ym=YYYY-MM）。
function archive_page(): void
{
    $ym = preg_match('/^\d{4}-\d{2}$/', (string)($_GET['ym'] ?? '')) ? (string)$_GET['ym'] : '';
    $page = current_page();
    $size = max(1, (int)setting('posts_per_page', '10'));
    $offset = ($page - 1) * $size;
    $where = 'status=1'; $params = [];
    if ($ym !== '') {
        $start = (int)strtotime($ym . '-01 00:00:00');
        $end = (int)strtotime('+1 month', $start);
        $where .= ' AND created_at>=? AND created_at<?'; $params = [$start, $end];
    }
    $total = (int)val("SELECT COUNT(*) FROM app_posts WHERE $where", $params);
    $posts = all("SELECT * FROM app_posts WHERE $where ORDER BY created_at DESC, id DESC LIMIT $size OFFSET $offset", $params);
    $title = $ym !== '' ? $ym . ' 归档' : '文章归档';
    $head = '<div class="card" style="padding:14px 20px;margin-bottom:16px"><strong>' . h($title) . '</strong> <span class="badge">' . $total . ' 篇</span></div>';
    $body = $head . render_post_list($posts, $total, $page, fn(int $p): string => route_url('archive', array_filter(['ym' => $ym, 'page' => $p])));
    page($title, shell_html($body, sidebar_html()));
}

// 搜索页：标题与正文 LIKE（跨库大小写处理）。
function search_page(): void
{
    $kw = trim((string)($_GET['q'] ?? ''));
    $page = current_page();
    $size = max(1, (int)setting('posts_per_page', '10'));
    $offset = ($page - 1) * $size;
    if ($kw === '') {
        page('搜索', shell_html('<div class="card"><form method="get" action="' . h(index_url()) . '"><input type="hidden" name="a" value="search">' . input('关键词', 'q', '', 'text', true) . '<button class="btn" type="submit">搜索</button></form></div>', sidebar_html()));
        return;
    }
    $like = '%' . $kw . '%';
    $op = db_driver() === 'pgsql' ? 'ILIKE' : 'LIKE';
    $where = "status=1 AND (title $op ? OR content $op ?)";
    $total = (int)val("SELECT COUNT(*) FROM app_posts WHERE $where", [$like, $like]);
    $posts = all("SELECT * FROM app_posts WHERE $where ORDER BY created_at DESC, id DESC LIMIT $size OFFSET $offset", [$like, $like]);
    $head = '<div class="card" style="padding:14px 20px;margin-bottom:16px"><strong>搜索“' . h($kw) . '”</strong> <span class="badge">' . $total . ' 条结果</span></div>';
    $body = $head . render_post_list($posts, $total, $page, fn(int $p): string => route_url('search', ['q' => $kw, 'page' => $p]), '没有找到相关文章。');
    page('搜索：' . $kw, shell_html($body, sidebar_html()));
}

// 独立页面（关于/友链等）：按 slug 渲染 Markdown 内容。
function page_page(): void
{
    $slug = trim((string)($_GET['slug'] ?? ''));
    $p = one('SELECT * FROM app_pages WHERE slug=?', [$slug]);
    if (!$p || ((int)$p['status'] !== 1 && !is_admin())) err('页面不存在', 404);
    $html = '';
    if ((int)$p['status'] !== 1) $html .= '<div class="note">这是一个草稿页面，仅管理员可见。</div>';
    $html .= '<article class="card post-detail">' . ((int)($p['show_title'] ?? 1) === 1 ? '<h1 class="post-title">' . h((string)$p['title']) . '</h1>' : '')
        . '<div class="content" data-slot="page.content">' . markdown_html((string)$p['content']) . '</div></article>';
    page((string)$p['title'], shell_html($html, sidebar_html()));
}

// 文章详情页：阅读数自增 + 正文 + 插件扩展区（评论插入点）。
function post_page(): void
{
    $p = row('app_posts', 'id', req_id());
    if (!$p || ((int)$p['status'] !== 1 && !is_admin())) err('文章不存在或已下线', 404);
    $pid = (int)$p['id'];
    if ((int)$p['status'] === 1) q('UPDATE app_posts SET view_count=view_count+1 WHERE id=?', [$pid]);
    $author = row('app_users', 'id', (int)$p['user_id']);
    $cat = (int)$p['category_id'] > 0 ? category_by_id((int)$p['category_id']) : null;
    $tags = posts_tags_map([$pid])[$pid] ?? [];

    $html = '<article class="card post-detail" data-post-id="' . $pid . '">';
    $html .= '<h1 class="post-title">' . h($p['title']) . '</h1>';
    $html .= '<div class="post-author">';
    $html .= '<img class="avatar" src="' . h(user_avatar_url($author, 80)) . '" alt="">';
    $html .= '<div><div class="name">' . h((string)($author['nickname'] ?? '匿名')) . '</div>';
    $html .= '<div class="post-meta" style="margin:0"><span>' . h(date('Y-m-d H:i', (int)$p['created_at'])) . '</span>';
    if ($cat) $html .= '<span>· <a href="' . h(route_url('category', ['id' => (int)$cat['id']])) . '">' . h($cat['name']) . '</a></span>';
    $html .= '<span>· ' . ((int)$p['view_count'] + ((int)$p['status'] === 1 ? 1 : 0)) . ' 阅读</span></div></div></div>';
    if ((int)$p['status'] !== 1) $html .= '<div class="note">这是一篇草稿，仅管理员可见。</div>';
    $html .= '<div class="content" data-slot="post.content">' . markdown_html((string)$p['content']) . '</div>';
    if ($tags) {
        $html .= '<div class="post-tags" style="margin-top:20px">';
        foreach ($tags as $t) $html .= '<a class="tag" href="' . h(route_url('tag', ['id' => (int)$t['id']])) . '">' . h($t['name']) . '</a>';
        $html .= '</div>';
    }
    // 文章操作区：管理员编辑/删除 + 插件扩展（点赞等），对所有访客触发 post.actions。
    $admin_ops = '';
    if (is_admin()) {
        $admin_ops .= '<a class="btn sm ghost" href="' . h(route_url('edit', ['id' => $pid])) . '">编辑</a>';
        $admin_ops .= post_action_form(route_url('delete', ['id' => $pid]), '删除', ['_method' => 'post'], 'btn sm danger', '确定删除这篇文章吗？');
    }
    $plugin_ops = (string)hook('post.actions', '', ['post' => $p]);
    if ($admin_ops !== '' || $plugin_ops !== '') {
        $html .= '<div class="btn-row" style="margin-top:20px;padding-top:16px;border-top:1px solid var(--line)" data-slot="post.actions">' . $admin_ops . $plugin_ops . '</div>';
    }
    $html .= '</article>';
    // 正文之后的扩展区（评论插件在此渲染列表与表单）。
    $html .= (string)hook('post.content_after', '', ['post' => $p, 'post_id' => $pid]);

    $seo = ['description' => post_excerpt((string)$p['content'], 120), 'canonical' => absolute_url(route_url('post', ['id' => $pid]))];
    page($p['title'], shell_html($html, sidebar_html()), $seo);
}

function absolute_url(string $url): string
{
    $scheme = auth_cookie_secure() ? 'https' : 'http';
    $host = (string)($_SERVER['HTTP_HOST'] ?? 'localhost');
    if (str_starts_with($url, 'http://') || str_starts_with($url, 'https://')) return $url;
    return $scheme . '://' . $host . (str_starts_with($url, '/') ? '' : '/') . $url;
}

// 计划任务：CLI 调用命令（本地执行、天然受信，无需令牌）。
function cron_cli_command(): string
{
    return 'php ' . APP_ROOT . '/index.php cron';
}

// 计划任务：HTTP 入口 URL（自动附带访问令牌；令牌首次使用时自动生成并保存，防止被任意触发）。
function cron_secret_url(): string
{
    $token = (string)setting('cron_token', '');
    if ($token === '') {
        $token = bin2hex(random_bytes(16));
        save_settings_values(['cron_token' => $token]);
    }
    return absolute_url(route_url('cron', ['token' => $token]));
}

// --- 17. 文章写入（标签同步、before/after save Hook）---
// 解析逗号/空格分隔的标签串，写入 app_tags 与 app_post_tags（整篇一次性，非循环查库放大）。
function sync_post_tags(int $post_id, string $tags_input): void
{
    q('DELETE FROM app_post_tags WHERE post_id=?', [$post_id]);
    $names = array_values(array_unique(array_filter(array_map(
        fn($t) => mb_substr(trim($t), 0, 40),
        preg_split('/[,，\s]+/u', $tags_input) ?: []
    ))));
    foreach ($names as $name) {
        app_db_upsert('app_tags', ['name' => $name, 'slug' => slugify($name) ?: md5($name)], ['name']);
        $tid = (int)val('SELECT id FROM app_tags WHERE name=?', [$name]);
        if ($tid > 0) app_db_insert_ignore('app_post_tags', ['post_id' => $post_id, 'tag_id' => $tid], ['post_id', 'tag_id']);
    }
}

// 保存文章（新建或编辑），返回文章 ID。$data 已过滤。
function save_post(array $data, int $post_id = 0): int
{
    $data = hook('post.before_save', $data, ['post_id' => $post_id]);
    if (!is_array($data)) err('保存数据无效');
    $tags_input = (string)($data['tags'] ?? '');
    $row = [
        'user_id' => (int)($data['user_id'] ?? uid()),
        'title' => mb_substr((string)$data['title'], 0, DB_STRING_MAX_LENGTH),
        'content' => (string)$data['content'],
        'category_id' => (int)($data['category_id'] ?? 0),
        'status' => (int)($data['status'] ?? 1) === 1 ? 1 : 0,
        'updated_at' => now(),
    ];
    // 文章级评论开关：仅评论插件启用时由写文章页提交；未启用时不动该列（保留原值/默认 1）。
    if (array_key_exists('allow_comment', $data)) $row['allow_comment'] = (int)$data['allow_comment'] === 1 ? 1 : 0;
    if ($post_id > 0) {
        $fields = array_keys($row);
        q('UPDATE app_posts SET ' . implode('=?,', $fields) . '=? WHERE id=?', array_merge(array_values($row), [$post_id]));
    } else {
        $row['created_at'] = now();
        $row['view_count'] = 0;
        $cols = array_keys($row);
        q('INSERT INTO app_posts(' . implode(',', $cols) . ') VALUES(' . sql_marks(count($cols)) . ')', array_values($row));
        $post_id = app_db_last_insert_id('app_posts');
    }
    sync_post_tags($post_id, $tags_input);
    fire('post.after_save', ['post_id' => $post_id, 'data' => $row]);
    return $post_id;
}

// 写文章 / 编辑文章共用表单页。
function write_page(): void
{
    need_admin();
    $post_id = req_id();
    $p = $post_id > 0 ? row('app_posts', 'id', $post_id) : null;
    if ($post_id > 0 && !$p) err('文章不存在', 404);
    if (is_post_request()) {
        $data = [
            'user_id' => $p ? (int)$p['user_id'] : uid(),
            'title' => post('title', DB_STRING_MAX_LENGTH),
            'content' => (string)($_POST['content'] ?? ''),
            'category_id' => (int)($_POST['category_id'] ?? 0),
            'status' => (int)($_POST['status'] ?? 1),
            'tags' => post('tags'),
        ];
        // 评论插件启用时，写文章页才有「允许评论」提交项；未启用时不提交、不覆盖列。
        if (isset(plugins()['comment'])) $data['allow_comment'] = (int)($_POST['allow_comment'] ?? 0) === 1 ? 1 : 0;
        if (trim($data['title']) === '') err('标题不能为空');
        if (trim($data['content']) === '') err('正文不能为空');
        $id = save_post($data, $post_id);
        set_flash($post_id > 0 ? '文章已更新' : ((int)$data['status'] === 1 ? '文章已发布' : '草稿已保存'));
        go(route_url('post', ['id' => $id]));
    }
    // 「未分类」不是分类，而是 category_id=0 的空状态（如分类被删除后）；
    // 「默认分类」是安装时创建的真实分类。新文章默认落入第一个分类，下拉不再常驻「未分类」选项。
    $cats = [];
    foreach (categories_cache() as $c) $cats[(string)$c['id']] = (string)$c['name'];
    $first_cat = (string)(array_key_first($cats) ?? '');
    $tag_names = [];
    if ($p) { foreach (posts_tags_map([(int)$p['id']])[(int)$p['id']] ?? [] as $t) $tag_names[] = $t['name']; }

    $title_v = (string)($p['title'] ?? '');
    $content_v = (string)($p['content'] ?? '');
    $cat_v = (string)($p['category_id'] ?? ($first_cat !== '' ? $first_cat : '0'));
    if ($cat_v !== '0' && !isset($cats[$cat_v])) $cat_v = $first_cat !== '' ? $first_cat : '0';
    if ($cat_v === '0') $cats = ['0' => '未分类'] + $cats; // 仅当文章当前无分类（分类被删/站点无分类）时才提供该兜底选项
    $status_v = (string)($p['status'] ?? '0'); // 新文章默认草稿，避免误发布
    $tags_v = implode(', ', $tag_names);
    // 「允许评论」是评论插件的配套项：仅插件启用时在表单中显示；默认勾选，不需要的文章自行取消。
    $comment_on = isset(plugins()['comment']);
    $comment_v = (int)($p['allow_comment'] ?? 1) === 1;

    $md_btn = static fn(string $act, string $label, string $title): string => '<button type="button" class="md-btn" data-md="' . h($act) . '" title="' . h($title) . '">' . $label . '</button>';
    $toolbar = $md_btn('bold', 'B', '加粗（Ctrl+B）') . $md_btn('italic', 'I', '斜体（Ctrl+I）') . $md_btn('strike', '<s>S</s>', '删除线') . $md_btn('code', '&lt;/&gt;', '行内代码')
        . '<span class="md-sep"></span>' . $md_btn('h2', 'H2', '二级标题') . $md_btn('h3', 'H3', '三级标题')
        . '<span class="md-sep"></span>' . $md_btn('ul', '• 列表', '无序列表') . $md_btn('ol', '1. 列表', '有序列表') . $md_btn('quote', '引用', '引用块')
        . '<span class="md-sep"></span>' . $md_btn('link', '链接', '链接（Ctrl+K）') . $md_btn('image', '图片', '图片') . $md_btn('codeblock', '代码块', '围栏代码块') . $md_btn('mermaid', '图表', 'Mermaid 图表') . $md_btn('table', '表格', '表格') . $md_btn('hr', '分割线', '分割线')
        . '<span class="md-spacer"></span>'
        . '<button type="button" class="md-btn md-toggle" data-role="split" title="分栏预览：右侧实时渲染" aria-pressed="false"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="12" y1="3" x2="12" y2="21"/></svg>分栏</button>'
        . '<button type="button" class="md-btn md-toggle" data-role="full" title="全屏写作（Esc 退出）" aria-pressed="false"><svg class="icon-max" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 3H5a2 2 0 0 0-2 2v3M21 8V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3M16 21h3a2 2 0 0 0 2-2v-3"/></svg><svg class="icon-min" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 3v3a2 2 0 0 1-2 2H3M21 8h-3a2 2 0 0 1-2-2V3M3 16h3a2 2 0 0 1 2 2v3M16 21v-3a2 2 0 0 1 2-2h3"/></svg>全屏</button>';

    $form = '<form method="post">' . form_token()
        . '<div class="write-line title-line">'
        . input('标题', 'title', $title_v, 'text', true)
        . select_input('状态', 'status', $status_v, ['1' => '发布', '0' => '草稿'])
        . '</div>'
        . '<div class="write-line meta-line">'
        . '<div class="cat-cell">' . select_input('分类', 'category_id', $cat_v, $cats)
        . '<button type="button" class="btn ghost cat-add" data-url="' . h(route_url('cat_add')) . '" title="新建分类" aria-label="新建分类">+</button></div>'
        . input('标签', 'tags', $tags_v, 'text', false, '用逗号或空格分隔')
        . ($comment_on ? checkbox('允许评论', 'allow_comment', $comment_v) : '')
        . '</div>'
        . '<div class="field-block">' . form_field_caption('正文', '支持 Markdown；快捷键 Ctrl+B / Ctrl+I / Ctrl+K 可用')
        . '<div class="md-editor" data-preview-url="' . h(route_url('md_render')) . '"><div class="md-toolbar" role="toolbar">' . $toolbar . '</div>'
        . '<div class="md-body"><textarea name="content" required>' . h($content_v) . '</textarea>'
        . '<div class="md-preview content"></div></div>'
        . '<div class="md-statusbar"><span class="md-count"></span></div></div></div>'
        . '<div class="btn-row write-actions"><button class="btn" type="submit">' . ($p ? '保存修改' : '保存文章') . '</button></div>'
        . '</form>';
    page($p ? '编辑文章' : '写文章', '<div class="wrap single"><div class="main"><div class="write-wrap"><div class="card"><h1 class="card-title" style="font-size:var(--font-size-xl)">' . ($p ? '编辑文章' : '写文章') . '</h1>' . $form . '</div></div></div></div>', [], true);
}

// Markdown 实时预览（写文章页分栏模式 AJAX 调用，返回渲染 HTML）。
function md_render_route(): void
{
    need_admin();
    require_post();
    json_response(['ok' => 1, 'html' => markdown_html((string)($_POST['content'] ?? ''))]);
}

// 快捷新建分类（写文章页 AJAX 调用，返回 JSON，不刷新页面保留草稿）。
function category_quick_add(): void
{
    need_admin();
    require_post();
    $name = post('name', DB_STRING_MAX_LENGTH);
    if ($name === '') json_response(['ok' => 0, 'message' => '分类名不能为空']);
    $exists = one('SELECT id FROM app_categories WHERE name=?', [$name]);
    if (!$exists) {
        q('INSERT INTO app_categories(name,slug,sort) VALUES(?,?,?)', [$name, slugify($name) ?: md5($name), 0]);
        $exists = ['id' => app_db_last_insert_id('app_categories')];
    }
    json_response(['ok' => 1, 'id' => (int)$exists['id'], 'name' => $name]);
}

// 删除文章（仅管理员，POST）。
function delete_route(): void
{
    need_admin();
    require_post();
    $post_id = req_id();
    $p = row('app_posts', 'id', $post_id);
    if (!$p) err('文章不存在', 404);
    fire('post.before_delete', ['post_id' => $post_id, 'post' => $p]);
    tx(function () use ($post_id) {
        q('DELETE FROM app_post_tags WHERE post_id=?', [$post_id]);
        q('DELETE FROM app_posts WHERE id=?', [$post_id]);
    });
    fire('post.after_delete', ['post_id' => $post_id]);
    set_flash('文章已删除');
    go(route_url('home'));
}

// --- 18. 登录 / 登出 ---
function login_page(): void
{
    if (me()) go(route_url('home'));
    if (is_post_request()) {
        $account = post('account');
        $password = (string)($_POST['password'] ?? '');
        $u = one('SELECT * FROM app_users WHERE email=? OR nickname=? LIMIT 1', [$account, $account]);
        if ($u && password_verify($password, (string)$u['password'])) {
            start_login((int)$u['id']);
            set_flash('登录成功');
            go(route_url('home'));
        }
        err('账号或密码错误');
    }
    $form = '<form method="post">' . form_token()
        . input('邮箱或昵称', 'account', '', 'text', true)
        . input('密码', 'password', '', 'password', true)
        . '<button class="btn" type="submit">登录</button></form>';
    $body = '<div class="install-wrap"><div class="card"><h1 class="card-title" style="font-size:var(--font-size-xl)">管理员登录</h1>'
        . (string)hook('login.after_form', $form, []) . '</div></div>';
    page('登录', $body, [], true);
}
function logout_route(): void
{
    clear_auth_cookie();
    set_flash('已退出登录');
    go(route_url('login'));
}

// --- 19. RSS（核心内置，插件可覆盖）---
function rss_route(): void
{
    header('Content-Type: application/rss+xml; charset=utf-8');
    $posts = all('SELECT * FROM app_posts WHERE status=1 ORDER BY created_at DESC, id DESC LIMIT 20');
    $site = setting('site_name', 'Mono');
    $link = absolute_url(route_url('home'));
    $xml = '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel>';
    $xml .= '<title>' . h($site) . '</title><link>' . h($link) . '</link><description>' . h(setting('site_description')) . '</description>';
    foreach ($posts as $p) {
        $url = absolute_url(route_url('post', ['id' => (int)$p['id']]));
        $xml .= '<item><title>' . h($p['title']) . '</title><link>' . h($url) . '</link><guid>' . h($url) . '</guid>'
            . '<pubDate>' . date(DATE_RSS, (int)$p['created_at']) . '</pubDate>'
            . '<description><![CDATA[' . post_excerpt((string)$p['content'], 300) . ']]></description></item>';
    }
    echo $xml . '</channel></rss>';
    exit;
}

// --- 20. 核心路由表与请求分发 ---
function core_routes(): array
{
    return [
        'home' => 'home_page',
        'post' => 'post_page',
        'category' => 'category_page',
        'tag' => 'tag_page',
        'archive' => 'archive_page',
        'search' => 'search_page',
        'write' => 'write_page',
        'edit' => 'write_page',
        'delete' => 'delete_route',
        'cat_add' => 'category_quick_add',
        'md_render' => 'md_render_route',
        'login' => 'login_page',
        'logout' => 'logout_route',
        'rss' => 'rss_route',
        'avatar' => 'avatar_route',
        'site_icon' => 'site_icon_route',
        'page' => 'page_page',
        'install' => [Setup::class, 'install_page'],
        'admin' => [Admin::class, 'route'],
    ];
}

// CLI 计划任务入口（供 cron 调用）。
if (PHP_SAPI === 'cli' && (string)($_SERVER['argv'][1] ?? '') === 'cron') {
    $_GET['a'] = 'cron';
    $_SERVER['REQUEST_METHOD'] = 'GET';
}

parse_path_route();
$route = (string)($_GET['a'] ?? 'home');

// 安装/升级：未安装时只放行安装相关路由。
if (!db_schema_ready()) {
    if ($route === 'install' && is_post_request()) Setup::install_run();
    Setup::install_page();
    exit;
}

// 插件目录同步（安装或后台触发后待处理）。
if (setting('plugin_sync_pending', '0') === '1') {
    Plugin::plugin_registry_sync();
    Plugin::plugin_assets_rebuild();
    save_settings_values(['plugin_sync_pending' => '0', 'plugin_assets_dirty' => '0']);
}

// 插件文件漂移自同步（DX）：开发期直接改 plugin.php 无需手动点「同步插件」，code_hash 不一致时自动重同步 + 重建合并资源。
Plugin::plugin_registry_autosync();

// 核心表结构升级（幂等；schema_version 门控避免每请求查列元数据）。
if ((int)setting('schema_version', '1') < 5) {
    Setup::upgrade_schema();
    save_settings_values(['schema_version' => '5']);
}

check();
fire('app.boot');

try {
    $handler = core_routes()[$route] ?? null;
    if ($route === 'cron') { Admin::cron_route(); }
    elseif ($handler !== null) { is_callable($handler) ? $handler() : err('页面不存在', 404); }
    elseif (!plugin_route($route)) err('你访问的页面不存在', 404);
} catch (Throwable $e) {
    if (is_admin() && $is_local) err('服务器错误：' . $e->getMessage() . ' @ ' . $e->getFile() . ':' . $e->getLine(), 500);
    error_log('[Mono] ' . $e->getMessage() . ' @ ' . $e->getFile() . ':' . $e->getLine());
    err('操作失败，请稍后重试', 500);
}
